### PR TITLE
More edits

### PR DESCRIPTION
**Pull request by zachary-foster**
Sorry for the late changes, but I found a few errors and wanted to make some minor changes to make teaching the RMarkdown section easier. @zkamvar: can you rebuild the site after merging?

### CODE REVIEW

**Comment by zkamvar** [comment]
I can do that.

I've been running into issues with extra directories using quiltr and I'm trying the RMarkdown way of doing things: http://rmarkdown.rstudio.com/rmarkdown_websites.html

I'll issue a pull request when I'm ready.

**Comment by zachary-foster** [comment]
Ok, sounds good. Are they temp directories in your home directory? I have noticed that bug occasionally, but its hard to find.

**Comment by zkamvar** [comment]
The culprits are usually 

.Rproj.user/ 
content

**Comment by zkamvar** [comment]
Hey Zach,

check out https://github.com/grunwaldlab/Reproducible-science-in-R/tree/test-gh-pages https://github.com/grunwaldlab/Reproducible-science-in-R/tree/test-gh-pages

and see if you're okay with this. I can easily switch to putting the TOC at the top, but I wanted to explore this way first.

Zhian

**Pull request merged**
